# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: docs.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndocs.proto\x12\x04\x64ocs\"!\n\x05Point\x12\x0b\n\x03lat\x18\x01 \x01(\x02\x12\x0b\n\x03lon\x18\x02 \x01(\x02\"\xde\x01\n\x13SaveDocumentRequest\x12\x12\n\narticle_id\x18\x01 \x01(\x05\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x04 \x01(\t\x12\x0c\n\x04lang\x18\x05 \x01(\t\x12\x1e\n\tlocations\x18\x06 \x03(\x0b\x32\x0b.docs.Point\x12\x17\n\x0fsemantic_vector\x18\x07 \x03(\x02\x12\x10\n\x08keywords\x18\x08 \x03(\t\x12\x10\n\x08\x65ntities\x18\t \x03(\t\x12\x0e\n\x06themes\x18\n \x03(\t\x12\r\n\x05\x63lass\x18\x0b \x03(\t\"$\n\x11SaveDocumentReply\x12\x0f\n\x07message\x18\x01 \x01(\t2\x9a\x01\n\tDocsSaver\x12\x44\n\x0cSaveDocument\x12\x19.docs.SaveDocumentRequest\x1a\x17.docs.SaveDocumentReply\"\x00\x12G\n\rSaveDocuments\x12\x19.docs.SaveDocumentRequest\x1a\x17.docs.SaveDocumentReply\"\x00(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'docs_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_POINT']._serialized_start=20
  _globals['_POINT']._serialized_end=53
  _globals['_SAVEDOCUMENTREQUEST']._serialized_start=56
  _globals['_SAVEDOCUMENTREQUEST']._serialized_end=278
  _globals['_SAVEDOCUMENTREPLY']._serialized_start=280
  _globals['_SAVEDOCUMENTREPLY']._serialized_end=316
  _globals['_DOCSSAVER']._serialized_start=319
  _globals['_DOCSSAVER']._serialized_end=473
# @@protoc_insertion_point(module_scope)
